### ISSUE TITLE
Horizon 介绍

### ISSUE THREAD

**Issue by fengyfei** [fengyfei/blog#10]
# Horizon

## 安装

docker-compose.yaml 文件如下：

```yml
rethink:
    container_name: rethink
    image: rethinkdb
    volumes:
      - ./rethink:/data
    ports:
      - "127.0.0.1:8120:8080"
      - "127.0.0.1:28015:28015"
    restart: always
  horizon:
    container_name: horizon
    image: rethinkdb/horizon
    command: su -s /bin/sh horizon -c "hz serve --dev --connect rethinkdb://rethink:28015 --bind all /usr/app"
    volumes:
      - ./horizon:/usr/app
    environment:
      - HZ_SECURE=false
    links:
      - rethink
    ports:
      - "8181:80"
```

可通过 docker-compose up -d 启动服务。
